### ISSUE TITLE
Filename logic is wrong

### ISSUE THREAD

**Issue by Quantumplation** [malorisdead/NeptunesPrideStateDownloader#1]
Through experimentation, I have observed that the following is true:

`report.productions` is the number of payments you have received, indexed by zero
`report.tick` is the number of in game hours that have passed since the start of the game
`report.production_counter` is the number of in game hours that have passed since the last production
`report.production_rate` is the number of in game hours between each payment

`report.tick_fragment` is used in real-time games, unsure of use
`report.tick_rate` is used in real-time games, and is the number of real life minutes that map to an in-game hour.

I cannot find a variable for how many in game hours each turn will advance the game.  It seems to be baked into the page itself on load, rather than the order.

**Comment by MechanicalMann** [comment]
Thanks for doing the research for me :smile:
